import { deleteCookie, getCookie, setCookie } from "@tanstack/react-start/server";
import type { ListInput, PublicUser, ReportResult, RowFilter } from "./types";

export const DEMO_ACCESS_COOKIE = "daalcrm_website_demo_access";
const DEMO_USER_ID = "00000000-0000-0000-0000-000000000001";
const DEMO_COOKIE_TTL_SECONDS = 60 * 60 * 2;

export type DemoLeadInput = {
  fullName: string;
  company: string;
  email: string;
  phone: string;
  teamSize: string;
  useCase: string;
  message?: string;
  website?: string;
};

export function isDemoRequest(): boolean {
  return getCookie(DEMO_ACCESS_COOKIE) === "1";
}

export function getDemoUser(): PublicUser {
  return {
    id: DEMO_USER_ID,
    email: "parham.lilian@demo.daalcrm.example",
    full_name: "پرهام لیلیان",
    avatar_url: null,
    phone: "۰۹۹۹۰۰۰۰۱۰۰",
    role: "admin",
    is_active: true,
    created_at: new Date(0).toISOString(),
  };
}

function setDemoAccessCookie(): void {
  setCookie(DEMO_ACCESS_COOKIE, "1", {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env["NODE_ENV"] === "production",
    path: "/",
    maxAge: DEMO_COOKIE_TTL_SECONDS,
  });
}

export function clearDemoAccess(): void {
  deleteCookie(DEMO_ACCESS_COOKIE, { path: "/" });
}

function clean(value: string | undefined, max = 500): string {
  return String(value ?? "")
    .trim()
    .slice(0, max);
}

function isEmail(value: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function validateDemoLead(input: DemoLeadInput): {
  fullName: string;
  company: string;
  email: string;
  phone: string;
  teamSize: string;
  useCase: string;
  message: string;
} {
  const fullName = clean(input.fullName, 120);
  const company = clean(input.company, 160);
  const email = clean(input.email, 180).toLowerCase();
  const phone = clean(input.phone, 60);
  const teamSize = clean(input.teamSize, 60);
  const useCase = clean(input.useCase, 160);
  const message = clean(input.message, 1000);

  if (clean(input.website, 120)) throw new Error("درخواست نامعتبر است.");
  if (fullName.length < 2) throw new Error("نام و نام خانوادگی را وارد کنید.");
  if (!company) throw new Error("نام شرکت را وارد کنید.");
  if (!email && !phone) throw new Error("حداقل ایمیل یا شماره تماس را وارد کنید.");
  if (email && !isEmail(email)) throw new Error("ایمیل واردشده معتبر نیست.");

  return { fullName, company, email, phone, teamSize, useCase, message };
}

/** فرم را بررسی می‌کند، دسترسی کوتاه‌مدت دمو می‌سازد و در صورت وجود دیتابیس سرنخ را ثبت می‌کند. */
export async function startDemo(input: DemoLeadInput): Promise<{ ok: true; persisted: boolean }> {
  validateDemoLead(input);
  setDemoAccessCookie();
  return { ok: true, persisted: false };
}

type DemoRow = Record<string, unknown> & { id: string };

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 864e5).toISOString();
const daysFromNow = (days: number) => new Date(now + days * 864e5).toISOString();

const DEMO_ROWS: Record<string, DemoRow[]> = {
  org_settings: [
    {
      id: "demo-org",
      org_name: "گروه فناوری دال",
      industry: "فناوری اطلاعات و نرم‌افزار",
      currency: "IRT",
      timezone: "Asia/Tehran",
      setup_completed: true,
      setup_step: 5,
      created_at: daysAgo(120),
      updated_at: daysAgo(1),
    },
  ],
  users: [
    {
      id: "demo-user-1",
      full_name: "پرهام لیلیان",
      email: "parham.lilian@demo.daalcrm.example",
      role: "admin",
      is_active: true,
      created_at: daysAgo(80),
      phone: "۰۹۹۹۰۰۰۰۱۰۰",
    },
    {
      id: "demo-user-2",
      full_name: "میثم رضایی",
      email: "meysam.rezaei@demo.daalcrm.example",
      role: "manager",
      is_active: true,
      created_at: daysAgo(48),
      phone: "۰۹۹۹۰۰۰۰۱۰۱",
    },
  ],
  companies: [
    {
      id: "demo-company-1",
      name: "راهکار نو",
      industry: "نرم‌افزار سازمانی",
      city: "تهران",
      phone: "۰۲۱۸۸۷۷۶۶۵۵",
      website: "https://customer-01.demo.daalcrm.example",
      size: "51-200",
      created_at: daysAgo(70),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-company-2",
      name: "ابرنگار",
      industry: "خدمات ابری",
      city: "مشهد",
      phone: "۰۵۱۳۷۶۵۴۳۲۱",
      website: "https://customer-02.demo.daalcrm.example",
      size: "11-50",
      created_at: daysAgo(44),
      updated_at: daysAgo(4),
    },
    {
      id: "demo-company-3",
      name: "پیشگامان شرق",
      industry: "مرکز تماس",
      city: "تهران",
      phone: "۰۲۱۴۴۵۵۶۶۷۷",
      website: "https://customer-03.demo.daalcrm.example",
      size: "200+",
      created_at: daysAgo(30),
      updated_at: daysAgo(1),
    },
    {
      id: "demo-company-4",
      name: "نوآوران فردا",
      industry: "مشاوره کسب‌وکار",
      city: "اصفهان",
      phone: "۰۳۱۳۶۲۴۱۲۳۴",
      website: "https://customer-04.demo.daalcrm.example",
      size: "1-10",
      created_at: daysAgo(12),
      updated_at: daysAgo(3),
    },
  ],
  contacts: [
    {
      id: "demo-contact-1",
      full_name: "سارا محمدی",
      email: "sara@demo.daalcrm.example",
      phone: "۰۹۱۲۱۱۱۲۲۳۳",
      job_title: "مدیر فروش",
      company_id: "demo-company-1",
      source: "وب‌سایت",
      hesabfa_code: "HF-DAAL-001",
      notes: "به دنبال یکپارچه‌سازی مسیر سرنخ تا قرارداد است.",
      created_at: daysAgo(6),
      updated_at: daysAgo(1),
    },
    {
      id: "demo-contact-2",
      full_name: "رضا نادری",
      email: "reza@demo.daalcrm.example",
      phone: "۰۹۱۵۳۳۴۴۵۵۶",
      job_title: "مدیرعامل",
      company_id: "demo-company-2",
      source: "معرفی",
      hesabfa_code: "HF-DAAL-002",
      notes: "نسخه تیمی و گزارش فروش برایش مهم است.",
      created_at: daysAgo(10),
      updated_at: daysAgo(4),
    },
    {
      id: "demo-contact-3",
      full_name: "نگار کریمی",
      email: "negar@demo.daalcrm.example",
      phone: "۰۹۱۹۸۸۷۷۶۶۵",
      job_title: "مدیر عملیات",
      company_id: "demo-company-3",
      source: "تماس ورودی",
      hesabfa_code: "HF-DAAL-003",
      notes: "در مرحله بررسی راه‌اندازی مرکز تماس است.",
      created_at: daysAgo(14),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-contact-4",
      full_name: "آرمان توکلی",
      email: "arman@demo.daalcrm.example",
      phone: "۰۹۱۳۴۴۵۶۷۸۹",
      job_title: "مدیر توسعه",
      company_id: "demo-company-4",
      source: "نمایشگاه",
      hesabfa_code: "HF-DAAL-004",
      notes: "برای مدیریت فرصت‌های B2B درخواست اطلاعات کرده است.",
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
    },
    {
      id: "demo-contact-5",
      full_name: "مهدی صادقی",
      email: "mehdi@demo.daalcrm.example",
      phone: "۰۹۱۲۴۴۴۵۵۶۶",
      job_title: "کارشناس فروش",
      company_id: "demo-company-1",
      source: "اینستاگرام",
      notes: "پیگیری برای آموزش تیم.",
      created_at: daysAgo(21),
      updated_at: daysAgo(7),
    },
    {
      id: "demo-contact-6",
      full_name: "پریسا اکبری",
      email: "parisa@demo.daalcrm.example",
      phone: "۰۹۱۵۶۶۷۷۸۸۹",
      job_title: "مسئول مالی",
      company_id: "demo-company-2",
      source: "تماس ورودی",
      created_at: daysAgo(32),
      updated_at: daysAgo(9),
    },
  ],
  deals: [
    {
      id: "demo-deal-1",
      title: "راه‌اندازی مرکز تماس",
      amount: 336000000,
      currency: "IRT",
      stage: "proposal",
      probability: 60,
      contact_id: "demo-contact-3",
      company_id: "demo-company-3",
      seller_id: "demo-user-2",
      users: { full_name: "میثم رضایی" },
      expected_close_date: daysFromNow(14),
      created_at: daysAgo(28),
      updated_at: daysAgo(1),
    },
    {
      id: "demo-deal-2",
      title: "اشتراک سالانه تیم فروش",
      amount: 148000000,
      currency: "IRT",
      stage: "negotiation",
      probability: 75,
      contact_id: "demo-contact-1",
      company_id: "demo-company-1",
      seller_id: "demo-user-1",
      users: { full_name: "پرهام لیلیان" },
      expected_close_date: daysFromNow(8),
      created_at: daysAgo(19),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-deal-3",
      title: "اتوماسیون پیگیری مشتریان",
      amount: 76800000,
      currency: "IRT",
      stage: "qualified",
      probability: 35,
      contact_id: "demo-contact-2",
      company_id: "demo-company-2",
      seller_id: "demo-user-2",
      users: { full_name: "میثم رضایی" },
      expected_close_date: daysFromNow(24),
      created_at: daysAgo(11),
      updated_at: daysAgo(4),
    },
    {
      id: "demo-deal-4",
      title: "راه‌اندازی داشبورد مدیران",
      amount: 92000000,
      currency: "IRT",
      stage: "new",
      probability: 20,
      contact_id: "demo-contact-4",
      company_id: "demo-company-4",
      seller_id: "demo-user-1",
      users: { full_name: "پرهام لیلیان" },
      expected_close_date: daysFromNow(32),
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
    },
    {
      id: "demo-deal-5",
      title: "تمدید پشتیبانی سازمانی",
      amount: 184000000,
      currency: "IRT",
      stage: "won",
      probability: 100,
      contact_id: "demo-contact-5",
      company_id: "demo-company-1",
      seller_id: "demo-user-2",
      users: { full_name: "میثم رضایی" },
      expected_close_date: daysAgo(5),
      created_at: daysAgo(42),
      updated_at: daysAgo(5),
    },
  ],
  activities: [
    {
      id: "demo-activity-1",
      subject: "تماس با سارا محمدی",
      type: "call",
      body: "بررسی نیازهای تیم فروش",
      contact_id: "demo-contact-1",
      deal_id: "demo-deal-2",
      invoice_id: "demo-invoice-1",
      due_at: daysFromNow(0),
      done: false,
      status: "in_progress",
      created_at: daysAgo(1),
      updated_at: daysAgo(1),
      contacts: { full_name: "سارا محمدی" },
      deals: { title: "اشتراک سالانه تیم فروش" },
      invoices: { invoice_no: 1042 },
    },
    {
      id: "demo-activity-2",
      subject: "ارسال پیشنهاد نسخه سازمانی",
      type: "email",
      body: "پیشنهاد قیمت و زمان راه‌اندازی ارسال شود.",
      contact_id: "demo-contact-3",
      deal_id: "demo-deal-1",
      invoice_id: "demo-invoice-3",
      due_at: daysFromNow(0),
      done: false,
      status: "in_progress",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
      contacts: { full_name: "نگار کریمی" },
      deals: { title: "راه‌اندازی مرکز تماس" },
      invoices: { invoice_no: 1040 },
    },
    {
      id: "demo-activity-3",
      subject: "جلسه کشف نیاز",
      type: "meeting",
      body: "بررسی روند فعلی پیگیری مشتریان",
      contact_id: "demo-contact-2",
      deal_id: "demo-deal-3",
      due_at: daysFromNow(1),
      done: false,
      status: "in_progress",
      created_at: daysAgo(4),
      updated_at: daysAgo(4),
      contacts: { full_name: "رضا نادری" },
      deals: { title: "اتوماسیون پیگیری مشتریان" },
    },
    {
      id: "demo-activity-4",
      subject: "پیگیری تمدید اشتراک",
      type: "task",
      body: "تماس با تیم مالی",
      contact_id: "demo-contact-5",
      deal_id: "demo-deal-5",
      invoice_id: "demo-invoice-2",
      due_at: daysFromNow(3),
      done: false,
      status: "deferred",
      created_at: daysAgo(8),
      updated_at: daysAgo(8),
      contacts: { full_name: "مهدی صادقی" },
      deals: { title: "تمدید پشتیبانی سازمانی" },
      invoices: { invoice_no: 1041 },
    },
    {
      id: "demo-activity-5",
      subject: "ارسال کاتالوگ محصول",
      type: "email",
      body: "",
      contact_id: "demo-contact-4",
      deal_id: "demo-deal-4",
      due_at: daysAgo(1),
      done: true,
      status: "done",
      created_at: daysAgo(9),
      updated_at: daysAgo(1),
      contacts: { full_name: "آرمان توکلی" },
      deals: { title: "راه‌اندازی داشبورد مدیران" },
    },
  ],
  invoices: [
    {
      id: "demo-invoice-1",
      invoice_no: 1042,
      contact_id: "demo-contact-1",
      deal_id: "demo-deal-2",
      seller_id: "demo-user-1",
      users: { full_name: "پرهام لیلیان" },
      subtotal: 148000000,
      discount: 0,
      total: 148000000,
      paid_amount: 74000000,
      status: "partial",
      issued_at: daysAgo(7),
      created_at: daysAgo(7),
      updated_at: daysAgo(2),
      contacts: { full_name: "سارا محمدی" },
    },
    {
      id: "demo-invoice-2",
      invoice_no: 1041,
      contact_id: "demo-contact-5",
      deal_id: "demo-deal-5",
      seller_id: "demo-user-2",
      users: { full_name: "میثم رضایی" },
      subtotal: 184000000,
      discount: 10000000,
      total: 174000000,
      paid_amount: 174000000,
      status: "paid",
      issued_at: daysAgo(12),
      created_at: daysAgo(12),
      updated_at: daysAgo(5),
      contacts: { full_name: "مهدی صادقی" },
    },
    {
      id: "demo-invoice-3",
      invoice_no: 1040,
      contact_id: "demo-contact-3",
      deal_id: "demo-deal-1",
      seller_id: "demo-user-2",
      users: { full_name: "میثم رضایی" },
      subtotal: 336000000,
      discount: 0,
      total: 336000000,
      paid_amount: 0,
      status: "unpaid",
      issued_at: daysAgo(3),
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
      contacts: { full_name: "نگار کریمی" },
    },
  ],
  payments: [
    {
      id: "demo-payment-1",
      invoice_id: "demo-invoice-1",
      contact_id: "demo-contact-1",
      amount: 74000000,
      method: "bank_transfer",
      paid_at: daysAgo(2),
      reference: "TRX-28431",
      created_at: daysAgo(2),
    },
    {
      id: "demo-payment-2",
      invoice_id: "demo-invoice-2",
      contact_id: "demo-contact-5",
      amount: 174000000,
      method: "card",
      paid_at: daysAgo(5),
      reference: "POS-18742",
      created_at: daysAgo(5),
    },
  ],
  payment_transactions: [
    {
      id: "demo-payment-tx-1",
      invoice_id: "demo-invoice-1",
      provider: "zarinpal",
      authority: "DEMO-AUTH-1042",
      amount: 74000000,
      currency: "IRT",
      status: "succeeded",
      ref_id: "DEMO-REF-8401",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-payment-tx-2",
      invoice_id: "demo-invoice-3",
      provider: "zarinpal",
      authority: "DEMO-AUTH-1040",
      amount: 336000000,
      currency: "IRT",
      status: "pending",
      ref_id: null,
      created_at: daysAgo(1),
      updated_at: daysAgo(1),
    },
  ],
  automations: [
    {
      id: "demo-automation-1",
      name: "پیگیری سرنخ جدید",
      description: "بعد از ثبت سرنخ، برای مسئول فروش وظیفه بساز.",
      trigger_type: "contact_created",
      actions: [{ type: "create_task" }],
      is_active: true,
      created_at: daysAgo(30),
      updated_at: daysAgo(4),
    },
    {
      id: "demo-automation-2",
      name: "یادآوری معامله‌های بدون حرکت",
      description: "معامله‌هایی که سه روز تغییر نکرده‌اند بررسی شوند.",
      trigger_type: "scheduled",
      actions: [{ type: "create_task" }, { type: "ai_summarize" }],
      is_active: true,
      created_at: daysAgo(18),
      updated_at: daysAgo(3),
    },
    {
      id: "demo-automation-3",
      name: "خوش‌آمدگویی سرنخ وب‌سایت",
      description: "برای سرنخ‌های جدید پیام آماده شود.",
      trigger_type: "contact_created",
      actions: [{ type: "send_sms" }],
      is_active: false,
      created_at: daysAgo(12),
      updated_at: daysAgo(12),
    },
  ],
  automation_runs: [
    {
      id: "demo-run-1",
      automation_id: "demo-automation-1",
      status: "success",
      message: "وظیفه برای سارا محمدی ساخته شد.",
      created_at: daysAgo(1),
      automations: { name: "پیگیری سرنخ جدید" },
    },
    {
      id: "demo-run-2",
      automation_id: "demo-automation-2",
      status: "success",
      message: "۳ معامله برای بررسی پیدا شد.",
      created_at: daysAgo(2),
      automations: { name: "یادآوری معامله‌های بدون حرکت" },
    },
  ],
  ai_agents: [
    {
      id: "demo-agent-1",
      name: "دستیار فروش دال",
      role: "خلاصه‌سازی و اولویت‌بندی فرصت‌های فروش",
      model: "gpt-5-mini",
      system_prompt: "به تیم فروش در اولویت‌بندی قدم بعدی کمک کن.",
      temperature: 0.4,
      is_active: true,
      created_at: daysAgo(22),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-agent-2",
      name: "دستیار پیگیری",
      role: "پیشنهاد متن پیگیری برای سرنخ‌ها",
      model: "gemini-3.5-flash",
      system_prompt: "متن‌های کوتاه و حرفه‌ای فارسی پیشنهاد بده.",
      temperature: 0.6,
      is_active: true,
      created_at: daysAgo(15),
      updated_at: daysAgo(6),
    },
  ],
  integrations: [
    {
      id: "demo-integration-1",
      kind: "sms",
      provider: "kavenegar",
      display_name: "پیامک کاوه‌نگار",
      config: {},
      is_enabled: false,
      created_at: daysAgo(120),
    },
    {
      id: "demo-integration-2",
      kind: "email",
      provider: "smtp",
      display_name: "ایمیل تراکنشی SMTP",
      config: {},
      is_enabled: true,
      created_at: daysAgo(120),
    },
    {
      id: "demo-integration-3",
      kind: "voip",
      provider: "asterisk",
      display_name: "تلفن گویا (Asterisk / Issabel)",
      config: {},
      is_enabled: false,
      created_at: daysAgo(120),
    },
    {
      id: "demo-integration-4",
      kind: "ai_openai",
      provider: "openai",
      display_name: "OpenAI",
      config: {},
      is_enabled: true,
      created_at: daysAgo(90),
    },
    {
      id: "demo-integration-5",
      kind: "ai_gemini",
      provider: "gemini",
      display_name: "Google Gemini",
      config: {},
      is_enabled: false,
      created_at: daysAgo(90),
    },
    {
      id: "demo-integration-6",
      kind: "ai_compatible",
      provider: "openai-compatible",
      display_name: "OpenAI-compatible / Local AI",
      config: {},
      is_enabled: false,
      created_at: daysAgo(90),
    },
    {
      id: "demo-integration-8",
      kind: "accounting_hesabfa",
      provider: "hesabfa",
      display_name: "حسابفا · حسابداری",
      config: {},
      is_enabled: true,
      created_at: daysAgo(60),
    },
    {
      id: "demo-integration-9",
      kind: "payment_zarinpal",
      provider: "zarinpal",
      display_name: "زرین‌پال · درگاه پرداخت",
      config: {},
      is_enabled: true,
      created_at: daysAgo(60),
    },
  ],
  services: [
    {
      id: "demo-service-1",
      name: "اشتراک سالانه تیم فروش",
      category: "اشتراک",
      duration_min: 60,
      price: 148000000,
      is_active: true,
      created_at: daysAgo(60),
    },
    {
      id: "demo-service-2",
      name: "راه‌اندازی و آموزش",
      category: "راه‌اندازی",
      duration_min: 180,
      price: 85000000,
      is_active: true,
      created_at: daysAgo(50),
    },
    {
      id: "demo-service-3",
      name: "پشتیبانی سازمانی",
      category: "پشتیبانی",
      duration_min: 120,
      price: 92000000,
      is_active: true,
      created_at: daysAgo(45),
    },
  ],
  campaigns: [
    {
      id: "demo-campaign-1",
      name: "پیگیری سرنخ‌های گرم شهریور",
      channel: "sms",
      status: "sent",
      audience: "سرنخ‌های گرم",
      scheduled_at: daysAgo(4),
      sent_count: 42,
      created_at: daysAgo(8),
    },
    {
      id: "demo-campaign-2",
      name: "خبرنامه مشتریان فعال",
      channel: "email",
      status: "scheduled",
      audience: "مشتریان فعال",
      scheduled_at: daysFromNow(2),
      sent_count: 0,
      created_at: daysAgo(3),
    },
  ],
  loyalty_transactions: [
    {
      id: "demo-loyalty-1",
      contact_id: "demo-contact-1",
      points: 120,
      reason: "تمدید اشتراک",
      created_at: daysAgo(4),
      contacts: { full_name: "سارا محمدی" },
    },
    {
      id: "demo-loyalty-2",
      contact_id: "demo-contact-2",
      points: 80,
      reason: "معرفی مشتری جدید",
      created_at: daysAgo(9),
      contacts: { full_name: "رضا نادری" },
    },
  ],
  affiliates: [
    {
      id: "demo-affiliate-1",
      name: "شبکه همکاران فناوری",
      email: "partners@demo.daalcrm.example",
      phone: "۰۲۱۸۸۷۷۶۶۵۵",
      code: "TECH-01",
      commission_percent: 8,
      status: "active",
      bank_account: null,
      created_at: daysAgo(42),
    },
    {
      id: "demo-affiliate-2",
      name: "مشاوران رشد فردا",
      email: "growth@demo.daalcrm.example",
      phone: "۰۹۱۲۳۳۴۴۵۵۶",
      code: "GROWTH-02",
      commission_percent: 10,
      status: "active",
      bank_account: null,
      created_at: daysAgo(21),
    },
  ],
  affiliate_referrals: [
    {
      id: "demo-referral-1",
      affiliate_id: "demo-affiliate-1",
      contact_id: "demo-contact-2",
      company_id: "demo-company-2",
      status: "meeting_held",
      commission_percent: 8,
      converted_value: 76800000,
      commission_amount: 6144000,
      meeting_at: daysAgo(2),
      introduction_channel: "لینک ارجاع",
      referred_at: daysAgo(14),
      affiliates: { name: "شبکه همکاران فناوری", code: "TECH-01" },
      contacts: { full_name: "رضا نادری" },
      companies: { name: "ابرنگار" },
    },
    {
      id: "demo-referral-2",
      affiliate_id: "demo-affiliate-2",
      contact_id: "demo-contact-4",
      company_id: "demo-company-4",
      status: "lead",
      commission_percent: 10,
      converted_value: 0,
      commission_amount: 0,
      meeting_at: null,
      introduction_channel: "معرفی مستقیم",
      referred_at: daysAgo(3),
      affiliates: { name: "مشاوران رشد فردا", code: "GROWTH-02" },
      contacts: { full_name: "آرمان توکلی" },
      companies: { name: "نوآوران فردا" },
    },
  ],
};

/** داده‌های تکمیلی دمو؛ همه دامنه‌ها عمداً زیر .example هستند و به سرویس واقعی وصل نیستند. */
const EXTRA_DEMO_ROWS: Record<string, DemoRow[]> = {
  users: [
    {
      id: "demo-user-3",
      full_name: "سارا نوروزی",
      email: "sara.norouzi@demo.daalcrm.example",
      role: "agent",
      is_active: true,
      created_at: daysAgo(36),
      phone: "۰۹۹۹۰۰۰۰۱۰۲",
    },
    {
      id: "demo-user-4",
      full_name: "نیما شریفی",
      email: "nima.sharifi@demo.daalcrm.example",
      role: "marketing",
      is_active: true,
      created_at: daysAgo(29),
      phone: "۰۹۹۹۰۰۰۰۱۰۳",
    },
    {
      id: "demo-user-5",
      full_name: "الهام کاظمی",
      email: "elham.kazemi@demo.daalcrm.example",
      role: "practitioner",
      is_active: true,
      created_at: daysAgo(21),
      phone: "۰۹۹۹۰۰۰۰۱۰۴",
    },
    {
      id: "demo-user-6",
      full_name: "امیرحسین مرادی",
      email: "amir.moradi@demo.daalcrm.example",
      role: "agent",
      is_active: true,
      created_at: daysAgo(14),
      phone: "۰۹۹۹۰۰۰۰۱۰۵",
    },
  ],
  companies: [
    {
      id: "demo-company-5",
      name: "داده‌گستر آفتاب",
      industry: "خدمات داده و نرم‌افزار",
      city: "تهران",
      phone: "۰۲۱۹۱۰۰۰۲۰۵",
      website: "https://customer-05.demo.daalcrm.example",
      size: "11-50",
      created_at: daysAgo(27),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-company-6",
      name: "مسیر ابری سپهر",
      industry: "خدمات ابری",
      city: "مشهد",
      phone: "۰۵۱۹۱۰۰۰۲۰۶",
      website: "https://customer-06.demo.daalcrm.example",
      size: "51-200",
      created_at: daysAgo(24),
      updated_at: daysAgo(3),
    },
    {
      id: "demo-company-7",
      name: "پیشرو لجستیک پارس",
      industry: "لجستیک و زنجیره تأمین",
      city: "تهران",
      phone: "۰۲۱۹۱۰۰۰۲۰۷",
      website: "https://customer-07.demo.daalcrm.example",
      size: "200+",
      created_at: daysAgo(20),
      updated_at: daysAgo(1),
    },
    {
      id: "demo-company-8",
      name: "سلامت‌یار نوین",
      industry: "سلامت دیجیتال",
      city: "شیراز",
      phone: "۰۷۱۹۱۰۰۰۲۰۸",
      website: "https://customer-08.demo.daalcrm.example",
      size: "11-50",
      created_at: daysAgo(18),
      updated_at: daysAgo(4),
    },
    {
      id: "demo-company-9",
      name: "بازرگانی آریا",
      industry: "بازرگانی و توزیع",
      city: "اصفهان",
      phone: "۰۳۱۹۱۰۰۰۲۰۹",
      website: "https://customer-09.demo.daalcrm.example",
      size: "51-200",
      created_at: daysAgo(16),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-company-10",
      name: "سازه‌پردازان شرق",
      industry: "مهندسی و ساخت‌وساز",
      city: "تبریز",
      phone: "۰۴۱۹۱۰۰۰۲۱۰",
      website: "https://customer-10.demo.daalcrm.example",
      size: "200+",
      created_at: daysAgo(13),
      updated_at: daysAgo(1),
    },
  ],
  contacts: [
    {
      id: "demo-contact-7",
      full_name: "نیلوفر رحیمی",
      email: "niloufar.rahimi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۰۷",
      job_title: "مدیر فروش",
      company_id: "demo-company-5",
      source: "وب‌سایت",
      notes: "به دنبال نظم دادن به سرنخ‌های ورودی و گزارش‌گیری تیم فروش است.",
      created_at: daysAgo(5),
      updated_at: daysAgo(1),
      companies: { name: "داده‌گستر آفتاب" },
    },
    {
      id: "demo-contact-8",
      full_name: "کسرا مرادی",
      email: "kasra.moradi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۰۸",
      job_title: "مدیرعامل",
      company_id: "demo-company-5",
      source: "معرفی",
      notes: "تصمیم‌گیرنده اصلی برای خرید اشتراک سازمانی.",
      created_at: daysAgo(8),
      updated_at: daysAgo(2),
      companies: { name: "داده‌گستر آفتاب" },
    },
    {
      id: "demo-contact-9",
      full_name: "لیلا نادری",
      email: "leila.naderi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۰۹",
      job_title: "مدیر عملیات",
      company_id: "demo-company-6",
      source: "تماس ورودی",
      notes: "می‌خواهد پیگیری تیم خدمات ابری قابل اندازه‌گیری باشد.",
      created_at: daysAgo(12),
      updated_at: daysAgo(3),
      companies: { name: "مسیر ابری سپهر" },
    },
    {
      id: "demo-contact-10",
      full_name: "فرهاد رستگار",
      email: "farhad.rostegar@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۰",
      job_title: "مدیر مالی",
      company_id: "demo-company-6",
      source: "نمایشگاه",
      notes: "تمرکز روی فاکتور، پرداخت و کنترل بدهی مشتریان دارد.",
      created_at: daysAgo(15),
      updated_at: daysAgo(5),
      companies: { name: "مسیر ابری سپهر" },
    },
    {
      id: "demo-contact-11",
      full_name: "یاسین صادقی",
      email: "yasin.sadeghi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۱",
      job_title: "مدیر فناوری",
      company_id: "demo-company-7",
      source: "وب‌سایت",
      notes: "یکپارچه‌سازی و داشبورد مدیران برایش اولویت دارد.",
      created_at: daysAgo(19),
      updated_at: daysAgo(4),
      companies: { name: "پیشرو لجستیک پارس" },
    },
    {
      id: "demo-contact-12",
      full_name: "شیرین کریمی",
      email: "shirin.karimi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۲",
      job_title: "سرپرست فروش",
      company_id: "demo-company-7",
      source: "همکار فروش",
      notes: "نیازمند توزیع سرنخ بین کارشناسان فروش است.",
      created_at: daysAgo(22),
      updated_at: daysAgo(6),
      companies: { name: "پیشرو لجستیک پارس" },
    },
    {
      id: "demo-contact-13",
      full_name: "کاوه رحیمی",
      email: "kaveh.rahimi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۳",
      job_title: "مدیرعامل",
      company_id: "demo-company-8",
      source: "تماس ورودی",
      notes: "برای پیگیری بیماران و قراردادهای سازمانی دمو می‌خواهد.",
      created_at: daysAgo(25),
      updated_at: daysAgo(2),
      companies: { name: "سلامت‌یار نوین" },
    },
    {
      id: "demo-contact-14",
      full_name: "مونا موسوی",
      email: "mona.mousavi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۴",
      job_title: "مدیر موفقیت مشتری",
      company_id: "demo-company-8",
      source: "وب‌سایت",
      notes: "گزارش فعالیت‌های تیم و یادآوری پیگیری‌ها را دنبال می‌کند.",
      created_at: daysAgo(28),
      updated_at: daysAgo(7),
      companies: { name: "سلامت‌یار نوین" },
    },
    {
      id: "demo-contact-15",
      full_name: "همایون اکبری",
      email: "homayoun.akbari@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۵",
      job_title: "مدیر توسعه کسب‌وکار",
      company_id: "demo-company-9",
      source: "نمایشگاه",
      notes: "برای مدیریت فرصت‌های چندمرحله‌ای درخواست جلسه داده است.",
      created_at: daysAgo(31),
      updated_at: daysAgo(9),
      companies: { name: "بازرگانی آریا" },
    },
    {
      id: "demo-contact-16",
      full_name: "الناز کاظمی",
      email: "elnaz.kazemi@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۶",
      job_title: "کارشناس قراردادها",
      company_id: "demo-company-9",
      source: "معرفی",
      notes: "پیگیری وضعیت پیشنهادها و قراردادها را انجام می‌دهد.",
      created_at: daysAgo(34),
      updated_at: daysAgo(8),
      companies: { name: "بازرگانی آریا" },
    },
    {
      id: "demo-contact-17",
      full_name: "بهنام حق‌گو",
      email: "behnam.haghgoo@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۷",
      job_title: "مدیر عملیات",
      company_id: "demo-company-10",
      source: "همکار فروش",
      notes: "به ثبت جلسات و فعالیت‌های تیم پروژه نیاز دارد.",
      created_at: daysAgo(38),
      updated_at: daysAgo(10),
      companies: { name: "سازه‌پردازان شرق" },
    },
    {
      id: "demo-contact-18",
      full_name: "شقایق جلیلی",
      email: "shaghayegh.jalili@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۲۱۸",
      job_title: "مدیر ارتباط با مشتری",
      company_id: "demo-company-10",
      source: "اینستاگرام",
      notes: "در حال بررسی تمدید پشتیبانی و آموزش تیم است.",
      created_at: daysAgo(41),
      updated_at: daysAgo(11),
      companies: { name: "سازه‌پردازان شرق" },
    },
  ],
  deals: [
    {
      id: "demo-deal-6",
      title: "استقرار CRM فروش داده‌گستر آفتاب",
      amount: 198000000,
      currency: "IRT",
      stage: "proposal",
      probability: 65,
      contact_id: "demo-contact-7",
      company_id: "demo-company-5",
      seller_id: "demo-user-3",
      users: { full_name: "سارا نوروزی" },
      expected_close_date: daysFromNow(11),
      created_at: daysAgo(15),
      updated_at: daysAgo(1),
      contacts: { full_name: "نیلوفر رحیمی" },
      companies: { name: "داده‌گستر آفتاب" },
    },
    {
      id: "demo-deal-7",
      title: "اشتراک سازمانی مسیر ابری سپهر",
      amount: 240000000,
      currency: "IRT",
      stage: "negotiation",
      probability: 70,
      contact_id: "demo-contact-9",
      company_id: "demo-company-6",
      seller_id: "demo-user-1",
      users: { full_name: "پرهام لیلیان" },
      expected_close_date: daysFromNow(6),
      created_at: daysAgo(22),
      updated_at: daysAgo(2),
      contacts: { full_name: "لیلا نادری" },
      companies: { name: "مسیر ابری سپهر" },
    },
    {
      id: "demo-deal-8",
      title: "اتوماسیون پیگیری لجستیک پارس",
      amount: 315000000,
      currency: "IRT",
      stage: "qualified",
      probability: 45,
      contact_id: "demo-contact-11",
      company_id: "demo-company-7",
      seller_id: "demo-user-3",
      users: { full_name: "سارا نوروزی" },
      expected_close_date: daysFromNow(19),
      created_at: daysAgo(18),
      updated_at: daysAgo(5),
      contacts: { full_name: "یاسین صادقی" },
      companies: { name: "پیشرو لجستیک پارس" },
    },
    {
      id: "demo-deal-9",
      title: "راه‌اندازی مرکز تماس سلامت‌یار",
      amount: 420000000,
      currency: "IRT",
      stage: "proposal",
      probability: 55,
      contact_id: "demo-contact-13",
      company_id: "demo-company-8",
      seller_id: "demo-user-4",
      users: { full_name: "نیما شریفی" },
      expected_close_date: daysFromNow(27),
      created_at: daysAgo(25),
      updated_at: daysAgo(3),
      contacts: { full_name: "کاوه رحیمی" },
      companies: { name: "سلامت‌یار نوین" },
    },
    {
      id: "demo-deal-10",
      title: "داشبورد مدیریتی بازرگانی آریا",
      amount: 168000000,
      currency: "IRT",
      stage: "new",
      probability: 20,
      contact_id: "demo-contact-15",
      company_id: "demo-company-9",
      seller_id: "demo-user-1",
      users: { full_name: "پرهام لیلیان" },
      expected_close_date: daysFromNow(35),
      created_at: daysAgo(4),
      updated_at: daysAgo(4),
      contacts: { full_name: "همایون اکبری" },
      companies: { name: "بازرگانی آریا" },
    },
    {
      id: "demo-deal-11",
      title: "پشتیبانی سازمانی سازه‌پردازان",
      amount: 286000000,
      currency: "IRT",
      stage: "won",
      probability: 100,
      contact_id: "demo-contact-17",
      company_id: "demo-company-10",
      seller_id: "demo-user-3",
      users: { full_name: "سارا نوروزی" },
      expected_close_date: daysAgo(8),
      created_at: daysAgo(52),
      updated_at: daysAgo(8),
      contacts: { full_name: "بهنام حق‌گو" },
      companies: { name: "سازه‌پردازان شرق" },
    },
    {
      id: "demo-deal-12",
      title: "تمدید قرارداد داده‌گستر آفتاب",
      amount: 145000000,
      currency: "IRT",
      stage: "won",
      probability: 100,
      contact_id: "demo-contact-8",
      company_id: "demo-company-5",
      seller_id: "demo-user-1",
      users: { full_name: "پرهام لیلیان" },
      expected_close_date: daysAgo(12),
      created_at: daysAgo(58),
      updated_at: daysAgo(12),
      contacts: { full_name: "کسرا مرادی" },
      companies: { name: "داده‌گستر آفتاب" },
    },
    {
      id: "demo-deal-13",
      title: "ماژول وفاداری مسیر ابری",
      amount: 112000000,
      currency: "IRT",
      stage: "new",
      probability: 15,
      contact_id: "demo-contact-10",
      company_id: "demo-company-6",
      seller_id: "demo-user-4",
      users: { full_name: "نیما شریفی" },
      expected_close_date: daysFromNow(41),
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
      contacts: { full_name: "فرهاد رستگار" },
      companies: { name: "مسیر ابری سپهر" },
    },
    {
      id: "demo-deal-14",
      title: "پروژه داده و تحلیل سازه‌پردازان",
      amount: 188000000,
      currency: "IRT",
      stage: "lost",
      probability: 0,
      contact_id: "demo-contact-18",
      company_id: "demo-company-10",
      seller_id: "demo-user-3",
      users: { full_name: "سارا نوروزی" },
      expected_close_date: daysAgo(18),
      created_at: daysAgo(61),
      updated_at: daysAgo(18),
      contacts: { full_name: "شقایق جلیلی" },
      companies: { name: "سازه‌پردازان شرق" },
    },
  ],
  activities: [
    {
      id: "demo-activity-6",
      subject: "ارسال پیشنهاد داده‌گستر آفتاب",
      type: "email",
      body: "نسخه پیشنهادی قیمت و زمان استقرار برای نیلوفر رحیمی ارسال شود.",
      contact_id: "demo-contact-7",
      deal_id: "demo-deal-6",
      due_at: daysFromNow(0),
      done: false,
      status: "in_progress",
      created_at: daysAgo(1),
      updated_at: daysAgo(1),
      contacts: { full_name: "نیلوفر رحیمی" },
      deals: { title: "استقرار CRM فروش داده‌گستر آفتاب" },
    },
    {
      id: "demo-activity-7",
      subject: "تماس پیگیری مسیر ابری",
      type: "call",
      body: "درباره شرایط پرداخت و تعداد کاربران نهایی سؤال شود.",
      contact_id: "demo-contact-9",
      deal_id: "demo-deal-7",
      due_at: daysFromNow(1),
      done: false,
      status: "in_progress",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
      contacts: { full_name: "لیلا نادری" },
      deals: { title: "اشتراک سازمانی مسیر ابری سپهر" },
    },
    {
      id: "demo-activity-8",
      subject: "جلسه کشف نیاز لجستیک پارس",
      type: "meeting",
      body: "مراحل توزیع سرنخ و دسترسی مدیران بررسی شود.",
      contact_id: "demo-contact-11",
      deal_id: "demo-deal-8",
      due_at: daysFromNow(2),
      done: false,
      status: "in_progress",
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
      contacts: { full_name: "یاسین صادقی" },
      deals: { title: "اتوماسیون پیگیری لجستیک پارس" },
    },
    {
      id: "demo-activity-9",
      subject: "دموی مرکز تماس سلامت‌یار",
      type: "meeting",
      body: "نمایش روند ثبت تماس و گزارش عملکرد کارشناسان.",
      contact_id: "demo-contact-13",
      deal_id: "demo-deal-9",
      due_at: daysFromNow(4),
      done: false,
      status: "in_progress",
      created_at: daysAgo(4),
      updated_at: daysAgo(4),
      contacts: { full_name: "کاوه رحیمی" },
      deals: { title: "راه‌اندازی مرکز تماس سلامت‌یار" },
    },
    {
      id: "demo-activity-10",
      subject: "تماس اولیه با بازرگانی آریا",
      type: "call",
      body: "شناخت فرایند فعلی فروش و گزارش‌گیری.",
      contact_id: "demo-contact-15",
      deal_id: "demo-deal-10",
      due_at: daysAgo(1),
      done: true,
      status: "done",
      created_at: daysAgo(8),
      updated_at: daysAgo(1),
      contacts: { full_name: "همایون اکبری" },
      deals: { title: "داشبورد مدیریتی بازرگانی آریا" },
    },
    {
      id: "demo-activity-11",
      subject: "جلسه تحویل پشتیبانی سازه‌پردازان",
      type: "meeting",
      body: "تقویم آموزش تیم و کانال پشتیبانی نهایی شد.",
      contact_id: "demo-contact-17",
      deal_id: "demo-deal-11",
      due_at: daysAgo(6),
      done: true,
      status: "done",
      created_at: daysAgo(12),
      updated_at: daysAgo(6),
      contacts: { full_name: "بهنام حق‌گو" },
      deals: { title: "پشتیبانی سازمانی سازه‌پردازان" },
    },
    {
      id: "demo-activity-12",
      subject: "ارسال قرارداد تمدید آفتاب",
      type: "email",
      body: "نسخه نهایی قرارداد برای امضا ارسال شد.",
      contact_id: "demo-contact-8",
      deal_id: "demo-deal-12",
      due_at: daysAgo(10),
      done: true,
      status: "done",
      created_at: daysAgo(16),
      updated_at: daysAgo(10),
      contacts: { full_name: "کسرا مرادی" },
      deals: { title: "تمدید قرارداد داده‌گستر آفتاب" },
    },
    {
      id: "demo-activity-13",
      subject: "پیگیری تصمیم‌گیرنده مسیر ابری",
      type: "task",
      body: "برای جلسه با مدیرعامل زمان پیشنهادی بفرستید.",
      contact_id: "demo-contact-10",
      deal_id: "demo-deal-13",
      due_at: daysFromNow(5),
      done: false,
      status: "deferred",
      created_at: daysAgo(7),
      updated_at: daysAgo(4),
      contacts: { full_name: "فرهاد رستگار" },
      deals: { title: "ماژول وفاداری مسیر ابری" },
    },
    {
      id: "demo-activity-14",
      subject: "پاسخ به درخواست اطلاعات",
      type: "email",
      body: "کاتالوگ و نمونه داشبورد ارسال شد.",
      contact_id: "demo-contact-12",
      deal_id: "demo-deal-8",
      due_at: daysAgo(2),
      done: true,
      status: "done",
      created_at: daysAgo(9),
      updated_at: daysAgo(2),
      contacts: { full_name: "شیرین کریمی" },
      deals: { title: "اتوماسیون پیگیری لجستیک پارس" },
    },
    {
      id: "demo-activity-15",
      subject: "تنظیم جلسه با سلامت‌یار",
      type: "task",
      body: "جلسه با مدیر موفقیت مشتری هماهنگ شود.",
      contact_id: "demo-contact-14",
      deal_id: "demo-deal-9",
      due_at: daysFromNow(3),
      done: false,
      status: "in_progress",
      created_at: daysAgo(6),
      updated_at: daysAgo(3),
      contacts: { full_name: "مونا موسوی" },
      deals: { title: "راه‌اندازی مرکز تماس سلامت‌یار" },
    },
    {
      id: "demo-activity-16",
      subject: "ارسال معرفی‌نامه گروه فناوری دال",
      type: "email",
      body: "معرفی‌نامه و نمونه مسیر استقرار برای بازرگانی آریا ارسال شد.",
      contact_id: "demo-contact-16",
      deal_id: "demo-deal-10",
      due_at: daysFromNow(1),
      done: false,
      status: "in_progress",
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
      contacts: { full_name: "الناز کاظمی" },
      deals: { title: "داشبورد مدیریتی بازرگانی آریا" },
    },
    {
      id: "demo-activity-17",
      subject: "بازبینی وضعیت قراردادهای باز",
      type: "task",
      body: "معاملات بدون فعالیت در هفته اخیر بررسی شود.",
      contact_id: null,
      deal_id: null,
      due_at: daysFromNow(2),
      done: false,
      status: "in_progress",
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
    },
    {
      id: "demo-activity-18",
      subject: "جلسه داخلی تیم فروش دال",
      type: "meeting",
      body: "مرور قیف فروش، مالکیت سرنخ‌ها و برنامه هفته آینده.",
      contact_id: null,
      deal_id: null,
      due_at: daysAgo(3),
      done: true,
      status: "done",
      created_at: daysAgo(10),
      updated_at: daysAgo(3),
    },
    {
      id: "demo-activity-19",
      subject: "پیگیری قرارداد سلامت‌یار",
      type: "call",
      body: "درباره زمان‌بندی استقرار و آموزش تیم پیگیری شود.",
      contact_id: "demo-contact-13",
      deal_id: "demo-deal-9",
      due_at: daysFromNow(7),
      done: false,
      status: "in_progress",
      created_at: daysAgo(5),
      updated_at: daysAgo(2),
      contacts: { full_name: "کاوه رحیمی" },
      deals: { title: "راه‌اندازی مرکز تماس سلامت‌یار" },
    },
    {
      id: "demo-activity-20",
      subject: "یادآوری تمدید پشتیبانی",
      type: "task",
      body: "برای مشتریان نزدیک به تمدید، پیام یادآوری آماده شود.",
      contact_id: "demo-contact-18",
      deal_id: "demo-deal-14",
      due_at: daysAgo(4),
      done: false,
      status: "deferred",
      created_at: daysAgo(13),
      updated_at: daysAgo(4),
      contacts: { full_name: "شقایق جلیلی" },
      deals: { title: "پروژه داده و تحلیل سازه‌پردازان" },
    },
  ],
  invoices: [
    {
      id: "demo-invoice-4",
      invoice_no: 1039,
      contact_id: "demo-contact-7",
      deal_id: "demo-deal-6",
      seller_id: "demo-user-3",
      subtotal: 198000000,
      discount: 8000000,
      total: 190000000,
      paid_amount: 95000000,
      status: "partial",
      issued_at: daysAgo(5),
      created_at: daysAgo(5),
      updated_at: daysAgo(1),
      contacts: { full_name: "نیلوفر رحیمی" },
      deals: { title: "استقرار CRM فروش داده‌گستر آفتاب" },
      users: { full_name: "سارا نوروزی" },
    },
    {
      id: "demo-invoice-5",
      invoice_no: 1038,
      contact_id: "demo-contact-9",
      deal_id: "demo-deal-7",
      seller_id: "demo-user-1",
      subtotal: 240000000,
      discount: 0,
      total: 240000000,
      paid_amount: 0,
      status: "unpaid",
      issued_at: daysAgo(9),
      created_at: daysAgo(9),
      updated_at: daysAgo(4),
      contacts: { full_name: "لیلا نادری" },
      deals: { title: "اشتراک سازمانی مسیر ابری سپهر" },
      users: { full_name: "پرهام لیلیان" },
    },
    {
      id: "demo-invoice-6",
      invoice_no: 1037,
      contact_id: "demo-contact-11",
      deal_id: "demo-deal-8",
      seller_id: "demo-user-3",
      subtotal: 315000000,
      discount: 15000000,
      total: 300000000,
      paid_amount: 300000000,
      status: "paid",
      issued_at: daysAgo(17),
      created_at: daysAgo(17),
      updated_at: daysAgo(7),
      contacts: { full_name: "یاسین صادقی" },
      deals: { title: "اتوماسیون پیگیری لجستیک پارس" },
      users: { full_name: "سارا نوروزی" },
    },
    {
      id: "demo-invoice-7",
      invoice_no: 1036,
      contact_id: "demo-contact-13",
      deal_id: "demo-deal-9",
      seller_id: "demo-user-4",
      subtotal: 420000000,
      discount: 20000000,
      total: 400000000,
      paid_amount: 120000000,
      status: "partial",
      issued_at: daysAgo(14),
      created_at: daysAgo(14),
      updated_at: daysAgo(3),
      contacts: { full_name: "کاوه رحیمی" },
      deals: { title: "راه‌اندازی مرکز تماس سلامت‌یار" },
      users: { full_name: "نیما شریفی" },
    },
    {
      id: "demo-invoice-8",
      invoice_no: 1035,
      contact_id: "demo-contact-17",
      deal_id: "demo-deal-11",
      seller_id: "demo-user-3",
      subtotal: 286000000,
      discount: 0,
      total: 286000000,
      paid_amount: 286000000,
      status: "paid",
      issued_at: daysAgo(25),
      created_at: daysAgo(25),
      updated_at: daysAgo(16),
      contacts: { full_name: "بهنام حق‌گو" },
      deals: { title: "پشتیبانی سازمانی سازه‌پردازان" },
      users: { full_name: "سارا نوروزی" },
    },
  ],
  payments: [
    {
      id: "demo-payment-3",
      invoice_id: "demo-invoice-4",
      contact_id: "demo-contact-7",
      amount: 95000000,
      method: "bank_transfer",
      paid_at: daysAgo(1),
      reference: "DEMO-TRX-103",
      created_at: daysAgo(1),
    },
    {
      id: "demo-payment-4",
      invoice_id: "demo-invoice-6",
      contact_id: "demo-contact-11",
      amount: 300000000,
      method: "card",
      paid_at: daysAgo(7),
      reference: "DEMO-POS-104",
      created_at: daysAgo(7),
    },
    {
      id: "demo-payment-5",
      invoice_id: "demo-invoice-7",
      contact_id: "demo-contact-13",
      amount: 120000000,
      method: "bank_transfer",
      paid_at: daysAgo(3),
      reference: "DEMO-TRX-105",
      created_at: daysAgo(3),
    },
    {
      id: "demo-payment-6",
      invoice_id: "demo-invoice-8",
      contact_id: "demo-contact-17",
      amount: 286000000,
      method: "bank_transfer",
      paid_at: daysAgo(16),
      reference: "DEMO-TRX-106",
      created_at: daysAgo(16),
    },
  ],
  payment_transactions: [
    {
      id: "demo-payment-tx-3",
      invoice_id: "demo-invoice-4",
      provider: "zarinpal",
      authority: "DEMO-AUTH-1039",
      amount: 95000000,
      currency: "IRT",
      status: "succeeded",
      ref_id: "DEMO-REF-8402",
      created_at: daysAgo(1),
      updated_at: daysAgo(1),
    },
    {
      id: "demo-payment-tx-4",
      invoice_id: "demo-invoice-5",
      provider: "zarinpal",
      authority: "DEMO-AUTH-1038",
      amount: 240000000,
      currency: "IRT",
      status: "pending",
      ref_id: null,
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
    },
  ],
  automations: [
    {
      id: "demo-automation-4",
      name: "هشدار سرنخ‌های بدون پاسخ",
      description: "اگر سرنخ دو روز پیگیری نشد، برای مالک آن یادآوری بساز.",
      trigger_type: "activity_overdue",
      actions: [{ type: "create_task" }, { type: "send_email" }],
      is_active: true,
      created_at: daysAgo(9),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-automation-5",
      name: "خلاصه هفتگی قیف فروش دال",
      description: "هر هفته فرصت‌های مهم و معاملات بدون حرکت را خلاصه کن.",
      trigger_type: "scheduled",
      actions: [{ type: "ai_summarize" }],
      is_active: true,
      created_at: daysAgo(6),
      updated_at: daysAgo(1),
    },
  ],
  automation_runs: [
    {
      id: "demo-run-3",
      automation_id: "demo-automation-4",
      status: "success",
      message: "برای ۴ سرنخ بدون پاسخ، یادآوری ساخته شد.",
      created_at: daysAgo(3),
      automations: { name: "هشدار سرنخ‌های بدون پاسخ" },
    },
    {
      id: "demo-run-4",
      automation_id: "demo-automation-5",
      status: "success",
      message: "خلاصه هفتگی قیف فروش آماده شد.",
      created_at: daysAgo(4),
      automations: { name: "خلاصه هفتگی قیف فروش دال" },
    },
    {
      id: "demo-run-5",
      automation_id: "demo-automation-1",
      status: "success",
      message: "وظیفه برای نیلوفر رحیمی ساخته شد.",
      created_at: daysAgo(5),
      automations: { name: "پیگیری سرنخ جدید" },
    },
    {
      id: "demo-run-6",
      automation_id: "demo-automation-2",
      status: "success",
      message: "۵ معامله برای بررسی پیدا شد.",
      created_at: daysAgo(6),
      automations: { name: "یادآوری معامله‌های بدون حرکت" },
    },
  ],
  ai_agents: [
    {
      id: "demo-agent-3",
      name: "تحلیل‌گر قیف دال",
      role: "شناسایی فرصت‌های مهم و معاملات در خطر",
      model: "gpt-5-mini",
      system_prompt: "برای مدیر فروش، وضعیت قیف و قدم بعدی هر فرصت را خلاصه کن.",
      temperature: 0.3,
      is_active: true,
      created_at: daysAgo(12),
      updated_at: daysAgo(2),
    },
    {
      id: "demo-agent-4",
      name: "دستیار موفقیت مشتری",
      role: "پیشنهاد پیگیری و مراقبت از مشتریان فعال",
      model: "gemini-3.5-flash",
      system_prompt: "پیشنهادهای کوتاه و محترمانه برای حفظ و توسعه مشتری ارائه بده.",
      temperature: 0.5,
      is_active: false,
      created_at: daysAgo(8),
      updated_at: daysAgo(8),
    },
  ],
  integrations: [
    {
      id: "demo-integration-7",
      kind: "postgres",
      provider: "postgres",
      display_name: "پایگاه‌داده PostgreSQL",
      config: {},
      is_enabled: true,
      created_at: daysAgo(120),
    },
    {
      id: "demo-integration-10",
      kind: "accounting_hesabfa",
      provider: "hesabfa",
      display_name: "حسابفا · حسابداری",
      config: {},
      is_enabled: true,
      created_at: daysAgo(60),
    },
    {
      id: "demo-integration-11",
      kind: "payment_zarinpal",
      provider: "zarinpal",
      display_name: "زرین‌پال · درگاه پرداخت",
      config: {},
      is_enabled: true,
      created_at: daysAgo(60),
    },
  ],
  services: [
    {
      id: "demo-service-4",
      name: "اشتراک سازمانی نامحدود",
      category: "اشتراک",
      duration_min: 60,
      price: 240000000,
      is_active: true,
      created_at: daysAgo(35),
    },
    {
      id: "demo-service-5",
      name: "راه‌اندازی مرکز تماس",
      category: "راه‌اندازی",
      duration_min: 240,
      price: 175000000,
      is_active: true,
      created_at: daysAgo(28),
    },
    {
      id: "demo-service-6",
      name: "داشبورد و گزارش مدیریتی",
      category: "تحلیل و گزارش",
      duration_min: 120,
      price: 68000000,
      is_active: true,
      created_at: daysAgo(20),
    },
    {
      id: "demo-service-7",
      name: "آموزش تیم فروش",
      category: "آموزش",
      duration_min: 180,
      price: 55000000,
      is_active: true,
      created_at: daysAgo(16),
    },
  ],
  campaigns: [
    {
      id: "demo-campaign-3",
      name: "دعوت به جلسه برای سرنخ‌های گرم",
      channel: "email",
      status: "draft",
      audience: "سرنخ‌های مرحله پیشنهاد",
      scheduled_at: daysFromNow(5),
      sent_count: 0,
      created_at: daysAgo(6),
    },
    {
      id: "demo-campaign-4",
      name: "یادآوری تمدید مشتریان سازمانی",
      channel: "sms",
      status: "sent",
      audience: "مشتریان نزدیک به تمدید",
      scheduled_at: daysAgo(10),
      sent_count: 18,
      created_at: daysAgo(14),
    },
    {
      id: "demo-campaign-5",
      name: "معرفی داشبورد مدیران",
      channel: "email",
      status: "scheduled",
      audience: "مخاطبین مدیرعامل و مدیر فناوری",
      scheduled_at: daysFromNow(8),
      sent_count: 0,
      created_at: daysAgo(2),
    },
  ],
  loyalty_transactions: [
    {
      id: "demo-loyalty-3",
      contact_id: "demo-contact-7",
      points: 150,
      reason: "شرکت در جلسه راه‌اندازی",
      created_at: daysAgo(3),
      contacts: { full_name: "نیلوفر رحیمی" },
    },
    {
      id: "demo-loyalty-4",
      contact_id: "demo-contact-11",
      points: 220,
      reason: "تمدید قرارداد سازمانی",
      created_at: daysAgo(11),
      contacts: { full_name: "یاسین صادقی" },
    },
    {
      id: "demo-loyalty-5",
      contact_id: "demo-contact-13",
      points: 90,
      reason: "معرفی همکار جدید",
      created_at: daysAgo(17),
      contacts: { full_name: "کاوه رحیمی" },
    },
    {
      id: "demo-loyalty-6",
      contact_id: "demo-contact-17",
      points: -40,
      reason: "لغو جلسه بدون اطلاع",
      created_at: daysAgo(23),
      contacts: { full_name: "بهنام حق‌گو" },
    },
  ],
  affiliates: [
    {
      id: "demo-affiliate-3",
      name: "شبکه مشاوران کسب‌وکار دال",
      email: "consultants@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۳۰۳",
      code: "DAAL-CONSULT-03",
      commission_percent: 7,
      status: "active",
      bank_account: null,
      created_at: daysAgo(33),
    },
    {
      id: "demo-affiliate-4",
      name: "همکاران تحول دیجیتال",
      email: "digital-partners@demo.daalcrm.example",
      phone: "۰۹۹۹۰۰۰۰۳۰۴",
      code: "DIGITAL-04",
      commission_percent: 12,
      status: "active",
      bank_account: null,
      created_at: daysAgo(18),
    },
  ],
  affiliate_referrals: [
    {
      id: "demo-referral-3",
      affiliate_id: "demo-affiliate-3",
      contact_id: "demo-contact-7",
      company_id: "demo-company-5",
      status: "proposal",
      commission_percent: 7,
      converted_value: 198000000,
      commission_amount: 13860000,
      meeting_at: daysAgo(4),
      introduction_channel: "معرفی مستقیم",
      referred_at: daysAgo(19),
      affiliates: { name: "شبکه مشاوران کسب‌وکار دال", code: "DAAL-CONSULT-03" },
      contacts: { full_name: "نیلوفر رحیمی" },
      companies: { name: "داده‌گستر آفتاب" },
    },
    {
      id: "demo-referral-4",
      affiliate_id: "demo-affiliate-4",
      contact_id: "demo-contact-13",
      company_id: "demo-company-8",
      status: "meeting_scheduled",
      commission_percent: 12,
      converted_value: 420000000,
      commission_amount: 0,
      meeting_at: daysFromNow(4),
      introduction_channel: "لینک ارجاع",
      referred_at: daysAgo(8),
      affiliates: { name: "همکاران تحول دیجیتال", code: "DIGITAL-04" },
      contacts: { full_name: "کاوه رحیمی" },
      companies: { name: "سلامت‌یار نوین" },
    },
    {
      id: "demo-referral-5",
      affiliate_id: "demo-affiliate-3",
      contact_id: "demo-contact-15",
      company_id: "demo-company-9",
      status: "introduced",
      commission_percent: 7,
      converted_value: 0,
      commission_amount: 0,
      meeting_at: null,
      introduction_channel: "معرفی مستقیم",
      referred_at: daysAgo(2),
      affiliates: { name: "شبکه مشاوران کسب‌وکار دال", code: "DAAL-CONSULT-03" },
      contacts: { full_name: "همایون اکبری" },
      companies: { name: "بازرگانی آریا" },
    },
  ],
};

for (const [table, rows] of Object.entries(EXTRA_DEMO_ROWS)) {
  DEMO_ROWS[table] = [...(DEMO_ROWS[table] ?? []), ...rows];
}

function splitSelect(select: string): string[] {
  const items: string[] = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < select.length; i += 1) {
    const char = select[i];
    if (char === "(") depth += 1;
    if (char === ")") depth -= 1;
    if (char === "," && depth === 0) {
      items.push(select.slice(start, i).trim());
      start = i + 1;
    }
  }
  items.push(select.slice(start).trim());
  return items.filter(Boolean);
}

function projectDemoRow(row: DemoRow, select?: string): DemoRow {
  if (!select || select.trim() === "*") return { ...row };
  const result: DemoRow = { id: row.id };
  for (const item of splitSelect(select)) {
    const nestedStart = item.indexOf("(");
    if (nestedStart > 0 && item.endsWith(")")) {
      const key = item.slice(0, nestedStart).trim();
      if (row[key] !== undefined) result[key] = row[key];
      continue;
    }
    const key = item.trim();
    if (row[key] !== undefined) result[key] = row[key];
  }
  return result;
}

function matchesFilter(row: DemoRow, filter: RowFilter): boolean {
  const value = row[filter.column];
  if (filter.op === "ilike")
    return String(value ?? "")
      .toLowerCase()
      .includes(String(filter.value ?? "").toLowerCase());
  if (filter.op === "in")
    return Array.isArray(filter.value) && filter.value.map(String).includes(String(value));
  if (filter.op === "eq") return String(value ?? "") === String(filter.value ?? "");
  if (filter.op === "neq") return String(value ?? "") !== String(filter.value ?? "");
  const left = Number(value);
  const right = Number(filter.value);
  if (Number.isNaN(left) || Number.isNaN(right)) return true;
  if (filter.op === "gt") return left > right;
  if (filter.op === "gte") return left >= right;
  if (filter.op === "lt") return left < right;
  if (filter.op === "lte") return left <= right;
  return true;
}

export function listDemoRows(input: ListInput): DemoRow[] {
  const rows = [...(DEMO_ROWS[input.table] ?? [])];
  const filtered = rows.filter((row) =>
    (input.filters ?? []).every((filter) => matchesFilter(row, filter)),
  );
  const orderBy = input.orderBy ?? "created_at";
  filtered.sort((a, b) => String(a[orderBy] ?? "").localeCompare(String(b[orderBy] ?? "")));
  if (input.ascending === false) filtered.reverse();
  const offset = Math.max(input.offset ?? 0, 0);
  const limit = Math.min(Math.max(input.limit ?? 200, 1), 1000);
  return filtered.slice(offset, offset + limit).map((row) => projectDemoRow(row, input.select));
}

export function getDemoReport(report: string): ReportResult {
  const reportRows: Record<string, Record<string, unknown>[]> = {
    revenue_by_month: [
      { month: "2026-06", total: 532000000, count: 5 },
      { month: "2026-07", total: 746000000, count: 8 },
      { month: "2026-08", total: 1124000000, count: 12 },
    ],
    invoice_status_summary: [
      { status: "paid", count: 3, total: 760000000, paid: 760000000 },
      { status: "partial", count: 3, total: 738000000, paid: 289000000 },
      { status: "unpaid", count: 2, total: 576000000, paid: 0 },
    ],
    invoice_debt_summary: [{ total: 2074000000, debt: 1025000000, pending_count: 5 }],
    payment_method_summary: [
      { method: "card", count: 2, total: 474000000 },
      { method: "bank_transfer", count: 4, total: 575000000 },
    ],
    payment_gateway_summary: [
      { provider: "zarinpal", status: "succeeded", count: 2, total: 169000000 },
      { provider: "zarinpal", status: "pending", count: 2, total: 576000000 },
    ],
    accounting_sync_summary: [{ total: 35, synced: 18 }],
    activities_by_status: [
      { status: "in_progress", count: 11 },
      { status: "done", count: 6 },
      { status: "deferred", count: 3 },
    ],
    activities_by_owner: [
      { owner: "پرهام لیلیان", count: 8, completed: 3 },
      { owner: "میثم رضایی", count: 6, completed: 2 },
      { owner: "سارا نوروزی", count: 4, completed: 1 },
      { owner: "نیما شریفی", count: 2, completed: 0 },
    ],
    new_contacts_by_month: [
      { month: "2026-06", count: 5 },
      { month: "2026-07", count: 8 },
      { month: "2026-08", count: 11 },
    ],
    pipeline_summary: [
      { stage: "new", count: 3, total: 372000000 },
      { stage: "qualified", count: 2, total: 391800000 },
      { stage: "proposal", count: 3, total: 954000000 },
      { stage: "negotiation", count: 2, total: 388000000 },
      { stage: "won", count: 3, total: 615000000 },
      { stage: "lost", count: 1, total: 188000000 },
    ],
    deals_won_by_month: [{ month: "2026-08", total: 615000000, count: 3 }],
    deals_won_by_seller: [
      { seller: "سارا نوروزی", count: 2, total: 586000000 },
      { seller: "میثم رضایی", count: 1, total: 184000000 },
    ],
    collections_by_seller: [
      { seller: "سارا نوروزی", count: 3, total: 501000000 },
      { seller: "پرهام لیلیان", count: 2, total: 248000000 },
    ],
    top_services: [
      { service: "اشتراک سازمانی نامحدود", revenue: 480000000, quantity: 2 },
      { service: "راه‌اندازی مرکز تماس", revenue: 420000000, quantity: 2 },
      { service: "داشبورد و گزارش مدیریتی", revenue: 204000000, quantity: 3 },
    ],
  };
  const rows = reportRows[report] ?? [];
  return { report, columns: rows[0] ? Object.keys(rows[0]) : [], rows };
}

/** ثبت درخواست دمو بدون نیاز به ورود؛ داده مستقیماً به سرنخ CRM تبدیل می‌شود. */
export async function createDemoLead(input: DemoLeadInput): Promise<{
  ok: true;
  contactId: string;
  created: boolean;
}> {
  validateDemoLead(input);
  return { ok: true, contactId: "", created: false };
}
